name: Run Unit Tests

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
        python-version: [3.11]  
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Run tests
        run: |
          python -m unittest discover tests
