name: Python package

on:
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ${{matrix.runner}}
    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu-latest, window-latest ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Test with unittest
      run: |
        unittest
